### ISSUE TITLE
Follow proper casing for API key config parameter

### ISSUE THREAD

**Issue by pmuens** [serverless/event-gateway-sdk#17]
Right now we follow `camelCase`, however the API key config follows lower case which might introduce confusion.

I'd propose to change this from `apikey` to `apiKey`.

**Comment by pmuens** [comment]
The `env` variable for the API should be updated as well (from `EVENT_GATEWAY_APIKEY` to `EVENT_GATEWAY_API_KEY`).

**Comment by alexdebrie** [comment]
Thanks, @pmuens.

@mthenw Thoughts?

**Comment by mthenw** [comment]
I think both are fine. My OCD is on lower level than Philipp's tho. 

I would leave it as it is.

**Comment by brianneisler** [comment]
I agree with Philipp here. These little things often lead to bugs that can
be hard to track down. Would be great to stay consistent as much as
possible.

**Comment by alexdebrie** [comment]
Closed in #19
