### ISSUE TITLE
Bug: Invoking functions seems to be broken.

### ISSUE THREAD

**Issue by eahefnawy** [serverless/event-gateway-sdk#31]
I get the following error when I try to invoke a function with the invoke method:

```
Failed to invoke function eg-test due the error: function or subscription not found
```

I've confirmed that both the function and the subscription exists by running the `listFunctions` and `listSubscriptions` methods.

**Comment by mthenw** [comment]
Hey @eahefnawy,

can you provide more details of your subscription and invoke request. I cannot reproduce that.

**Comment by mthenw** [comment]
@eahefnawy I'm closing this one. Let me know if you still have this issue.
