### ISSUE TITLE
Getting "process is undefined" error when using unpack build

### ISSUE THREAD

**Issue by pmuens** [serverless/event-gateway-sdk#41]
In `headers.js` we're using `process.env` to extract the Event Gateway access key --> https://github.com/serverless/event-gateway-sdk/blob/39bc74e1e1d8d5d886655ed0cf2c050fc076bca1/lib/utils/headers.js#L6

Using `process` will cause browser usage to fail since it's undefined.

We should add a check here to determine in which environment we're working and skip the `process.env` setting of the `accessKey` if we're in a browser

**Comment by mthenw** [comment]
Good catch. Wanna provide PR?
