### ISSUE TITLE
Emit method does not work with sync subscription

### ISSUE THREAD

**Issue by ac360** [serverless/event-gateway-sdk#49]
The EG appears to return a `202` status code when the subscription is set to `async` and a `200` status code when the subscription is set to `sync`.

The SDK currently only supports a `202` response, so it doesn't work with sync subscriptions.

I tried to implement a quick fix, but ran into some other strange behavior.  When you create both an `async` and `sync` subscription on the same path+method within the Event Gateway, the `async` subscription suddenly starts returning a `200` status code instead of a `202`.

Also ran into an issue where async events are firing twice via the SDK.  Ran out of time before I could figure this out.

All of this can be discovered by playing with these tests in Event Gateway & SDK, which are currently failing due to the above: 

https://github.com/serverless/event-gateway-sdk/tree/support-200

**Comment by mthenw** [comment]
> I tried to implement a quick fix, but ran into some other strange behavior. When you create both an async and sync subscription on the same path+method within the Event Gateway, the async subscription suddenly starts returning a 200 status code instead of a 202.

What would be your desired behavior here? Right now the default status code if not set in function response is 200. Should it be 202?

**Comment by mthenw** [comment]
After some thinking my proposition is to accept any status code <400 @ganeshvlrk @ac360 thoughts?

**Comment by ac360** [comment]
Sounds good to me @mthenw .  Will provide more feedback as I continue to use it in my example app.

**Comment by ganeshvlrk** [comment]
Thats reasonable. Sounds fine to me @mthenw
